[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:new-api]
command=/new-api --log-dir /app/logs
autostart=true
autorestart=true
stderr_logfile=/app/logs/new-api.err.log
stdout_logfile=/app/logs/new-api.out.log

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stderr_logfile=/var/log/nginx/error.log
stdout_logfile=/var/log/nginx/access.log
